// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dandeliondeathray/gooseberry/director (interfaces: Work,Dependency,EventPublisher)

package director_mock

import (
	director "github.com/dandeliondeathray/gooseberry/director"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockWork is a mock of Work interface
type MockWork struct {
	ctrl     *gomock.Controller
	recorder *MockWorkMockRecorder
}

// MockWorkMockRecorder is the mock recorder for MockWork
type MockWorkMockRecorder struct {
	mock *MockWork
}

// NewMockWork creates a new mock instance
func NewMockWork(ctrl *gomock.Controller) *MockWork {
	mock := &MockWork{ctrl: ctrl}
	mock.recorder = &MockWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockWork) EXPECT() *MockWorkMockRecorder {
	return m.recorder
}

// Schedule mocks base method
func (m *MockWork) Schedule() {
	m.ctrl.Call(m, "Schedule")
}

// Schedule indicates an expected call of Schedule
func (mr *MockWorkMockRecorder) Schedule() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockWork)(nil).Schedule))
}

// MockDependency is a mock of Dependency interface
type MockDependency struct {
	ctrl     *gomock.Controller
	recorder *MockDependencyMockRecorder
}

// MockDependencyMockRecorder is the mock recorder for MockDependency
type MockDependencyMockRecorder struct {
	mock *MockDependency
}

// NewMockDependency creates a new mock instance
func NewMockDependency(ctrl *gomock.Controller) *MockDependency {
	mock := &MockDependency{ctrl: ctrl}
	mock.recorder = &MockDependencyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDependency) EXPECT() *MockDependencyMockRecorder {
	return m.recorder
}

// Execute mocks base method
func (m *MockDependency) Execute() {
	m.ctrl.Call(m, "Execute")
}

// Execute indicates an expected call of Execute
func (mr *MockDependencyMockRecorder) Execute() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDependency)(nil).Execute))
}

// MockEventPublisher is a mock of EventPublisher interface
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// DependencyCompleted mocks base method
func (m *MockEventPublisher) DependencyCompleted(arg0 director.Dependency) {
	m.ctrl.Call(m, "DependencyCompleted", arg0)
}

// DependencyCompleted indicates an expected call of DependencyCompleted
func (mr *MockEventPublisherMockRecorder) DependencyCompleted(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DependencyCompleted", reflect.TypeOf((*MockEventPublisher)(nil).DependencyCompleted), arg0)
}

// DependencyExecuted mocks base method
func (m *MockEventPublisher) DependencyExecuted(arg0 director.Dependency) {
	m.ctrl.Call(m, "DependencyExecuted", arg0)
}

// DependencyExecuted indicates an expected call of DependencyExecuted
func (mr *MockEventPublisherMockRecorder) DependencyExecuted(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DependencyExecuted", reflect.TypeOf((*MockEventPublisher)(nil).DependencyExecuted), arg0)
}

// WorkCompleted mocks base method
func (m *MockEventPublisher) WorkCompleted(arg0 director.Work) {
	m.ctrl.Call(m, "WorkCompleted", arg0)
}

// WorkCompleted indicates an expected call of WorkCompleted
func (mr *MockEventPublisherMockRecorder) WorkCompleted(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkCompleted", reflect.TypeOf((*MockEventPublisher)(nil).WorkCompleted), arg0)
}

// WorkScheduled mocks base method
func (m *MockEventPublisher) WorkScheduled(arg0 director.Work) {
	m.ctrl.Call(m, "WorkScheduled", arg0)
}

// WorkScheduled indicates an expected call of WorkScheduled
func (mr *MockEventPublisherMockRecorder) WorkScheduled(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkScheduled", reflect.TypeOf((*MockEventPublisher)(nil).WorkScheduled), arg0)
}
